### ISSUE TITLE
Python 3.12 tracking issue

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#15277]
- [ ] PEP 688
- [ ] PEP 692 (#14697)
- [ ] PEP 695 (#15238, see issue for subtasks
- [x] PEP 698 (#14072, but missing strict mode)
- [ ] Change to which variables walrus can bind to in comprehensions https://github.com/python/cpython/pull/100581

**Comment by JukkaL** [comment]
Added "Fix mypyc" to the list.

**Comment by AlexWaygood** [comment]
Could add #15330 to the list

**Comment by JukkaL** [comment]
Mypyc now needs setuptools on 3.12 and later, which we don't yet include as a dependency.

**Comment by JukkaL** [comment]
Added "Require 3.12 tests to pass in CI".

**Comment by showierdata9978** [comment]
cannot ignore new generic system is not supported 
![image](https://github.com/python/mypy/assets/68120127/fe3a65b0-52df-45c4-95ee-d2aa43383ddb)

**Comment by CoolCat467** [comment]
With https://github.com/python/cpython/pull/100581 being merged, is walrus comprehension binding taken care of?

**Comment by ilevkivskyi** [comment]
I think all items here are implemented so this can be closed.
