### ISSUE TITLE
Python 3.13 tracking issue

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#17264]
- [x] PEP 696 (partially supported) https://github.com/python/mypy/issues/14851
- [x] PEP 702 https://github.com/python/mypy/issues/16111
- [x] PEP 742 (still needs documentation https://github.com/python/mypy/issues/17156)
- [x] PEP 705 (needs docs https://github.com/python/mypy/pull/17644)
- [x] Support `NamedTuple.__replace__` https://github.com/python/mypy/pull/17259
- [x] Require 3.13 tests to pass in CI https://github.com/python/mypy/pull/17812
- [x] Stubgen tests passing https://github.com/python/mypy/pull/17290 
- [x] Update mypyc to support 3.13 mypyc/mypyc#1056

See Python 3.12 tracking issue here: https://github.com/python/mypy/issues/15277

(feel free to edit this issue)

**Comment by hauntsaninja** [comment]
Thank you to @cdce8p for all your work towards making mypy/c work on 3.13!

**Comment by Sebcio03** [comment]
Anything I can help with?

**Comment by hauntsaninja** [comment]
Note for almost all use cases mypy 1.12 and newer will work great on Python 3.13

If you're interested in helping, one thing that isn't too hard is posting a summary in the PEP 696 and 702 issues of what remains to be done based on running mypy master against the conformance test suites in https://github.com/python/typing/tree/main/conformance

You could also take a look into what it would take to make mypy/mypyc work well with free threading. See https://github.com/mypyc/mypyc/issues/1038. One thing here could be to look into moving mypyc to use multi-phase module init, this would also help with subinterpreters in Python 3.12 and newer

**Comment by tyralla** [comment]
I had a look at the PEP 702-related part of the conformance test suite and found that Mypy's master branch misses one `E`. I sneaked the quick fix into the related PR #18090.

There are still two or three `E?`s that may require attention, and #18085 needs still discussion, but I think/hope Mypy 1.14 will cover the most frequent/relevant cases.

**Comment by mvanderlee** [comment]
Python 3.13 added `typing.NoDefault`: https://docs.python.org/3/library/typing.html#typing.NoDefault

Using it causes `error: Module "typing" has no attribute "NoDefault"  [attr-defined]`

**Comment by JelleZijlstra** [comment]
@mvanderlee `typing.NoDefault` is already present in mypy's bundled stubs (https://github.com/python/mypy/blob/c00f82f801b5d02c31c298fdcfafc40760357bfd/mypy/typeshed/stdlib/typing.pyi#L1064). I haven't tracked down when it was added, but it's likely that you're using an old version of mypy.

**Comment by hauntsaninja** [comment]
I think we can call this done
