### ISSUE TITLE
Release 0.530 planning

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#4009]
I'm getting ready to do a new mypy release. We're going to use a release branch that we'll cut 5-7 days before the actual release and then we'll cherry-pick only essential fixes to that branch.

- I'll cut the release branch on Friday, September 29.
- The tentative release date is Wednesday, October 4.

Please add to this issue PRs and fixes that you think need to be included in the release, but please be reasonable (if there's no PR yet we likely won't have time to finish the review by Friday).

I am expecting the following PRs to make it in, so no need to list these:

- [x] A typeshed sync (#4035) done right before I cut the branch
- [x] #4005 (user install on Windows)
- [x] #4002 (README.md update)
- [x] #3952 (Fix forward refs)
- [x] #3995 ("Partial" crashes)

**Comment by elazarg** [comment]
#3227

(If for some reason it's cosidered risky (I don't think it is), then I might be able to make a PR with only item 1 there, which fixes #3223)

**Comment by JukkaL** [comment]
The main announced features will be user-defined protocols and TypedDict as an official feature (assuming #3952 will be merged). Any testing of these two would be particularly valuable before the release.

**Comment by elazarg** [comment]
#4016 (Fix handling of non-method callable attribute)

(previous comment removed)

**Comment by ilevkivskyi** [comment]
I think it actually makes sense to add https://github.com/python/mypy/pull/3996, there were just two minor comments from @JukkaL and I implemented them yesterday. It would be nice if mypy and runtime implementation of protocols would agree.

**Comment by JukkaL** [comment]
I'm okay with including #3996. I'll check that it works with internal Dropbox codebases though.

**Comment by gvanrossum** [comment]
Now #3996 is merged I'm going to cut a release branch.

**Comment by gvanrossum** [comment]
The release branch now exists! If you need something to be cherry-picked there please list it in this issue, using this markup:
```
- [ ] #XXXX (description)
```
That way it'll come out as a checkbox that we can check when it's been cherry-picked into the branch. I will only cherry-pick PRs that have been merged into master first.

For typeshed please add "(typeshed)" to the name, as we will need to do some extra work to cherry-pick a typeshed-sync.

**Comment by gvanrossum** [comment]
Probably worth fixing, as it is a regression:
- [ ] #4046 (crash on asyncio.gather and tuple unpacking)

**Comment by JukkaL** [comment]
These documentation updates may be worth including, since they affect a newly released feature (protocols):

- [ ] #4050 (documentation updates only)

**Comment by gvanrossum** [comment]
- [ ] https://github.com/python/mypy/pull/4050 (Updates to documentation of type annotations and protocols)

**Comment by gvanrossum** [comment]
Maybe:
- [ ] #4051 (Never put None in TupleType items), since it fixes a seeming regression (but only seeming).

**Comment by gvanrossum** [comment]
Probably:
- [ ] #4045 (Delete cache if errors found), since it addresses a long-standing annoying crash.

**Comment by gvanrossum** [comment]
We're not doing either of those cherry-picks, since we don't have enough "burn-in time" until the release (Friday).

So unless something truly dramatic happens today or tomorrow, we're releasing Friday from exactly what's currently in the release-0.530 branch.

**Comment by gvanrossum** [comment]
(Except for https://github.com/python/mypy/pull/4057, which updates the revision history in the docs.)

**Comment by gvanrossum** [comment]
Mypy 0.530 is out! Protocols, support for TypedDict, and then some. Read the blog post. http://mypy-lang.blogspot.com/2017/10/mypy-0530-released.html

**Comment by gvanrossum** [comment]
(Oh, I never pushed the release branch to the master repo. I've now done so: https://github.com/python/mypy/tree/release-0.530.)
