### ISSUE TITLE
Literal types tracking issue

### ISSUE THREAD

**Issue by Michael0x2a** [python/mypy#5935]
This issue tracks TODOs for literal types.

## Core work

- [x] Modify the parser so it can handle literal expressions in types (https://github.com/python/mypy/pull/5947)
- [x] Make any necessary changes to semantic analysis (see below) (https://github.com/python/mypy/pull/5947)
- [x] Implement the core type-checking logic (also see below)
- [x] Implement logic for determining when and when not to infer Literal (https://github.com/python/mypy/pull/5990)
- [x] Validate that everything works in incremental mode and with the mypy daemon (https://github.com/python/mypy/pull/6075)
- [ ] Add "extra" features (again see below)
- [x] Write docs

## Parsing/semantic analysis follow-up tasks

- [x] Distinguish between byte strings, native strings, and unicode in Python 2 and Python 3 (https://github.com/python/mypy/pull/6087)
- [x] Make sure everything still works with `from __future__ import unicode_literals` (https://github.com/python/mypy/pull/6087)
- [x] Add more tests for forward references and related shenanigans
- [x] Add logic to make sure literal expressions are coerced to the correct type based on context (https://github.com/python/mypy/pull/5990)

## Error messages

- [x] Add better error messages for complex numbers (https://github.com/python/mypy/pull/6149)
- [x] Add better error messages for weird expressions in general (e.g. disallowing `Literal[1 + 2]`. This will probably involve moving *all* invalid type checking into the semantic analysis layer? (https://github.com/python/mypy/pull/6149)
- [x] Resolve https://github.com/python/mypy/issues/5989 (https://github.com/python/mypy/pull/6149)

## Implementing and testing type visitors

Implement and write tests that exercise the following visitors. (Introduced by https://github.com/python/mypy/pull/5934)

- [x] constraints.ConstraintBuilderVisitor (https://github.com/python/mypy/pull/5990)
- [x] join.TypeJoinVisitor (https://github.com/python/mypy/pull/5990)
- [x] meet.TypeMeetVisitor (https://github.com/python/mypy/pull/6043)
- [x] subtypes.ProperSubtypeVisitor (https://github.com/python/mypy/pull/5947)
- [x] subtypes.SubtypeVisitor (https://github.com/python/mypy/pull/5947)
- [x] typeanal.TypeAnalyzer (https://github.com/python/mypy/pull/5947)
- [x] typeanal.TypeAnalyzerPass3 (https://github.com/python/mypy/pull/5947)
- [x] types.TypeStrVisitor (https://github.com/python/mypy/pull/5947)
- [x] type_visitor.TypeVisitor (indirectly, by other tests)
- [x] type_visitor.TypeTranslator (indirectly, by other tests)

The following have preliminary implementations, but are missing associated tests:

- [x] erasetype.EraseTypeVisitor (indirectly, by https://github.com/python/mypy/pull/6035)
- [x] expandtype.ExpandTypeVisitor (indirectly, by https://github.com/python/mypy/pull/6035)
- [ ] fixup.TypeFixer (important for Enums)
- [x] sametypes.SameTypeVisitor (https://github.com/python/mypy/pull/6043)
- [x] server.astdiff.SnapshotTypeVisitor (https://github.com/python/mypy/pull/6075)
- [x] server.deps.TypeTriggersVisitor (https://github.com/python/mypy/pull/6075)

## Other checks to add in the type-checking layer

- [x] Make sure we cannot subclass Literals (https://github.com/python/mypy/pull/6034)
- [ ] Blacklist constructs like `Type[Literal[4]]`
    - Actually, should we? Maybe we should treat `Type[Literal[4]]` as `int` instead -- this might make certain TypeVar shenanigans more smooth. Need to discuss.
    - Actually, the above idea seems like a bad idea: if we do `x: Literal[3]`, doing `type(x)` ought to return a value with type `Type[int]`, not just `int`.
- [x] Blacklist using `Literal[...]` in `isinstance` and `issubclass` checks (https://github.com/python/mypy/pull/6034)
- [x] Validate `Literal` works as expected when used in generics (https://github.com/python/mypy/pull/6035)
- [ ] Consider having mypy warn if somebody tries doing literally `TypeVar('T', bound=Literal[4])`? Need to discuss first.

## "Extra" features to add

- [x] Intelligent indexing of tuples, NamedTuples, TypedDict, getattr, and setattr (https://github.com/python/mypy/pull/6124)
    - While I'm at it, design a more intelligent "macro replace" system and try and fix the misc errors we get when using `--disallow-any-expr`?
- [x] Type narrowing with equality and inequality checks
- [x] Interactions with `Final` (https://github.com/python/mypy/pull/6081)
- [x] Add custom type guards (see Ivan's comment below, also https://github.com/python/mypy/issues/5206)
- [x] Treat bool as a union of `Literal[True]` and `Literal[False]` (see https://github.com/python/mypy/issues/6113)

## Things to do before mypy 0.660 is released if literal types aren't going to make it

- [x] Address https://github.com/python/mypy/issues/5989 -- restore old error messages, and expunge any reference to literal types in any error messages we added. (https://github.com/python/mypy/pull/6121)

## Other things

- [x] Try replacing one of the functions we currently manage using plugins with literal types instead, and see what happens.
    - I tried replacing the "open(...)" plugin and re-ran mypy on one of our smaller internal codebases. Out of approximately 680 calls to `open`, about 610 of them had 2 or more arguments. We inferred the correct type for about 560 of those. About another 20 of these were passing in string variable arguments as the mode. The remaining 30 require a little more investigation -- some people were passing in `**kwargs` or `**args` in as the argument, etc...

## Things that have been deferred to after this project is completed

- Adding support for enums in literal types (and while I'm at it, I might as well investigate overhauling enums in general). Related tasks:
    - Treat enum classes as roughly a union of their values
    - Better error messages for bad imports (e.g. enums with a coerced type of 'Any')
- In error messages, we seem to quote types using either single quotes or double quotes. This can sometimes lead to messy-looking error messages (e.g. `Revealed type is 'Literal['foo']'`). We should standardize on a specific quoting scheme + avoid this weird "nesting" issue.
- Make sure we report an error when somebody tries doing `Literal[3]()` (and `Final[int]()` and `Protocol[blah]()`...)

**Comment by JukkaL** [comment]
The plan looks great! I'm looking forward to being able to use literal types.

**Comment by ilevkivskyi** [comment]
I think this idea already appeared somewhere, but I think it makes sense to add this to this list: custom type-guards (like in TypeScript):
```python
@overload
def is_spec(arg: Union[int, List[int]]) -> Literal[True]: ...
@overload
def is_spec(arg: object) -> bool: ...
def is_spec(arg):
    # some complex logic here
    ...

x: Union[int, str]
if is_spec(x):
    x += 42
```
essentially we just nee to teach binder how to interact with literals.

**Comment by ilevkivskyi** [comment]
@Michael0x2a I propose to use https://github.com/python/mypy/issues/5206 to track the type-guards idea (literals + binder).

**Comment by ethanhs** [comment]
There seem to be 3 relatively simple tasks left:

- Add tests for Literal and TypeFixer
- Disallow `Type[Literal[4]]`
- Disallow `TypeVar('T', bound=Literal[4])`

the last two in particular should be good first issues if I'm not mistaken.

**Comment by hauntsaninja** [comment]
I don't know that we need to error for the second one, and I feel we shouldn't disallow erroring for the third one (or any bound to a final type). I can't see what specific tests we'd want to add for the first one.
