### ISSUE TITLE
Supporting Python 3.9

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#9761]
The next release needs to support Python 3.9

Here's my checklist of what's left:
- [x] PEP 585 support (mostly #9564)
- [x] PEP 614 testing (#9759)
- [x] Merge and test new build process for 3.9 wheels (https://github.com/python/mypy/pull/9570, https://github.com/mypyc/mypy_mypyc-wheels/pull/11)
- [x] Add 3.9 to trove classifiers (https://github.com/python/mypy/pull/9887)
- [x] Improved documentation of PEP 563 + PEP 585 (#9763)
- [ ] mypy_extensions support for 3.9 (https://github.com/python/mypy_extensions/pull/20 / https://github.com/python/mypy_extensions/issues/21)

To clarify the state of support for users stumbling upon this issue, mypy 0.790 will mostly work with Python 3.9.
There are two caveats to running mypy with 3.9:
1) you won't be able to use `list[int]` syntax without mypy complaining,
2) mypy will be slower since we haven't released mypyc compiled wheels for 3.9.

Note that typeshed in 0.790 has pretty good support for Python 3.9, so using new stdlib functionality should work fine.

PS: if you're getting `error: syntax error in type comment` with Python 3.9, it's because you're using a really old mypy and you should upgrade to a recent release.

**Comment by intgr** [comment]
> The next release needs to support Python 3.9

I wouldn't make all of these hard requirements. I'd very much like to see a mypy release with binary wheels for 3.9 even before all of these items are addressed.

**Comment by gvanrossum** [comment]
Well, we still have the 0.790 release branch so we could just create wheels for that and push those. (Or make whatever tweak are necessary on that branch and push 0.791.)

**Comment by hauntsaninja** [comment]
@intgr Agreed that I wouldn't block an otherwise scheduled release on this, but there isn't currently a scheduled release / at this point the checklist^ isn't much additional effort to complete.

If someone with the ability to release is interested in adding 3.9 wheels to 0.790, you'll need to cherry pick #9552 and #9562 (and merge the aforementioned mypyc wheel repo change). Note mypyc is broken in the 0.790 sdist so you should cherry pick #9587 as well (see https://github.com/python/mypy/issues/9290#issuecomment-711131865).

**Comment by gvanrossum** [comment]
Here's hoping someone wants to take a stab!

**Comment by JukkaL** [comment]
We hopefully have a full release soonish, but again there are a lot of issues to address with Dropbox internal repos (previously these have mostly been typeshed issues). Otherwise there are no blockers for a new release.

I haven't had a lot of time to dedicate to mypy in the past weeks but I'm trying to carve out more time for it before the end of the year.

**Comment by bsolomon1124** [comment]
Mypy looks to be chugging along okay on 3.9 but (as expected, I understand this support has not been implemented yet) throws a bunch of `error: "<xxx>" is not subscriptable`. Related to https://github.com/python/mypy/issues/7239, is there a way to blanket-silence all `[misc]` error codes in mypy.ini?  (Even better would be the ability to silence by a pattern, such as `is not subscriptable`.)

**Comment by cdce8p** [comment]
@bsolomon1124 I don't know if that's of any help, but you could try installing the latest mypy commit with:
```bash
pip install -U git+git://github.com/python/mypy.git@master  # or replace `master` with commit hash
```
The `is not subscriptable` error was fixed with #9564, so this might be a temporary fix until the next version is released.

**Comment by hauntsaninja** [comment]
Just to follow up, if people want 3.9 wheels from latest master, they're available at https://github.com/mypyc/mypy_mypyc-wheels/releases/latest

**Comment by gvanrossum** [comment]
Can we get 3.10 wheels? :-)--
--Guido (mobile)

**Comment by hauntsaninja** [comment]
Not easily right now. We'd need 3.10 support in https://github.com/pypa/manylinux and https://github.com/joerick/cibuildwheel. But once that happens, it should be a two-liner.

**Comment by hauntsaninja** [comment]
mypy 0.800 has been released and includes all of^

**Comment by Hultner** [comment]
> mypy 0.800 has been released and includes all of^

Woho! Looking forward to try it out!

**Comment by wbadart** [comment]
Hey all- cross-posting my comment from #9564 in case anyone else has had issues with PEP 585 in type aliases: https://github.com/python/mypy/pull/9564#issuecomment-766909423
